### ISSUE TITLE
npx react-native init failed

### ISSUE THREAD

**Issue by tangkunyin** [microsoft/react-native#299]
Hi there, I refer to the instruction like below which was a pr has been merged https://github.com/microsoft/react-native/pull/291
```
Focus areas to test
Testing of this change was performed using a local copy of this branch, Verdaccio to run a local npm proxy, and react-native-macos and react-native-macos-init were published to the local Verdaccio server. Then the intended usage was tested:

$ npx react-native init AwesomeApp
$ cd AwesomeApp
$ npx react-native-macos-init
```
After installed the verdaccio proxy and push  code success
![image](https://user-images.githubusercontent.com/4197468/78982049-dd171180-7b53-11ea-8a65-ac67825313f8.png)

I tried to init my macOS app with npx, but it failed with: command not found: react-native

![image](https://user-images.githubusercontent.com/4197468/78981644-ee135300-7b52-11ea-9e7a-b289e194a9d3.png)

![image](https://user-images.githubusercontent.com/4197468/78982190-2d8e6f00-7b54-11ea-8e0a-ee1d0916922f.png)

**Comment by tangkunyin** [comment]
Since npx not work, I tried to install react-native as global：npm install react-native -g
After installed that, I init again：react-native init AwesomeApp

![image](https://user-images.githubusercontent.com/4197468/78983850-962b1b00-7b57-11ea-8644-7b0b0536699f.png)

It failed again....

Finally, I tried to add a verstion：react-native init AwesomeApp --version=latest

![image](https://user-images.githubusercontent.com/4197468/78984250-63355700-7b58-11ea-9bb4-c3e95d9f6fcc.png)
 
failed again....

**Comment by tom-un** [comment]
Hi @tangkunyin : the issue is because in this fork of react-native, the package.json name is still `"name": "react-native"` even though it is published to npmjs.org as `"react-native-macos"`.   In the build pipeline we run a script to rename the local copy in package.json to `"react-native-macos"` just prior to `npm publish`.   To work around this issue locally, you have to manually rename your local copy of package.json prior to publishing to verdaccio.

We have this backwards internal naming for legacy reasons.   I will be making a PR soon to make the name in package.json "react-native-macos" in the repo.

**Comment by tangkunyin** [comment]
@tom-un Thanks a lot
