### ISSUE TITLE
^0.61.0-microsoft.1 fails to build with "library not found for -lDoubleConversion-macOS"

### ISSUE THREAD

**Issue by mgcrea** [microsoft/react-native#328]
When attempting to build a brand new project using the latest `^0.61` release, I'm encountering the following error:

```
ld: library not found for -lDoubleConversion-macOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduction steps:

1. setup react-native

```sh
npx react-native init --template react-native-template-typescript SandboxProject
cd $_
git init
git add --all .; git ci -am "chore(git): npx react-native init"
```

2. setup react-native-macos

```sh
npx react-native-macos-init
find macos -type file -print0 | xargs -0 dos2unix
dos2unix react-native.config.js metro.config.macos.js
cd macos; pod install; cd -
echo "/macos/Pods/" >> .gitignore
git add --all .; git ci -am "chore(git): npx react-native-macos-init"
```

3. start 

```
xed -b macos
```

### Environment

```
▶ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.08 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by tom-un** [comment]
@mgcrea: I'm afraid I cannot repro this issue.   Our CI test for react-native-macos-init is passing.   I followed your steps above to the letter.   The only commands that fail for me are the `git ci` commands (don't know what those do, but they fail on my macs).   but i can open the project and built.   The packager launching is failing -- looks like `launchPackager.command` somehow got corrupted with DOS CRLF line endings.   But the app works anyway because I fixed the script that creates and copies that static jsbundle into the .app.    I'll fix `launchPackager.command`, but otherwise don't know why you are getting this error.   You are running XCode 11.4.1 and I'm running 11.3.1.   I'll try updating my XCode next.

**Comment by mgcrea** [comment]
@tom-un, sorry `git ci` is an alias to `git commit` on my mac. Did retry with the bare minimum without the git related stuff and not sure why but this time it did work.

It looks like the issue was that I did have un-properly closed and reopened the XCode project after doing the pod install. Sorry for the trouble, guess it will help people encountering this in the future.
